### PR TITLE
Using mbed namespace for block devices

### PR DESCRIPTION
**Pull request by bridadan**
This is a follow up to #39 and #38. This should be the least intrusive solution and also backwards compatible.

FYI @dlfryar

### CODE REVIEW

**Comment by bridadan** [comment]
Huh, looks like its not backwards compatible :/ any tips @0xc0170 @deepikabhavnani ?

**Comment by deepikabhavnani** [comment]
> Specifically wondering if its possible for storage-selector to work with BlockDevice living both in and out of the mbed namespace.

Since we have versions in Mbed OS, you use version number to have backward compatibility in storage selector (cannot think of better solution in Mbed OS).
```
Common_header.h 
#if Mbed OS version > 5.10
using namespace mbed;
#endif
```

**Comment by geky** [comment]
@pan- any idea on this puzzle?

BlockDevice moved to mbed::BlockDevice (on next minor release), but now it looks like there's no C++ way to be compatible with both, without ifdefs.

**Comment by deepikabhavnani** [comment]
FYI, Additional change coming in.. https://github.com/ARMmbed/mbed-os/pull/7747

**Comment by deepikabhavnani** [comment]
@geky - We also have https://github.com/ARMmbed/mbed-os/pull/7747

Does it make sense to typedef all?

**Comment by deepikabhavnani** [comment]
> It's probably better to use ifdefs with the mbed-os version. Then also the BlockDevice name can be kept the same.

Mbed OS version ifdefs will work only for released versions and not master :-(

**Comment by geky** [comment]
@deepikabhavnani Can't you also ifdef on the existance?

So somthing like:
```
#if !(defined(MBED_OS_VERSION) && MBED_OS_VERSION < 100)
typedef mbed::BlockDevice BlockDevice
#endif
```

**Comment by deepikabhavnani** [comment]
That will not work as on master version will always be 99 irrespective of when PR is merged. So different code based on SHA. We don't track SHA.

**Comment by geky** [comment]
My thinking was if you're on master we could assume you have the updated Mbed OS version, but you're right it's not a perfect solution.

**Comment by dlfryar** [comment]
We'd definitely need something that worked with master since there are often changes needed between releases for the full stack.  Especially in the case of Nordic boards.

**Comment by 0xc0170** [comment]
From what I was thinking and read here as proposals, I am still in favor of not having this in now - wait for the next major where we can do it with migration path.

**Comment by dlfryar** [comment]
@0xc0170 does that also imply backing out [PR#7663](url
https://github.com/ARMmbed/mbed-os/pull/7663) until such time?

**Comment by 0xc0170** [comment]
> @0xc0170 does that also imply backing out PR#7663 until such time?

Unfortunately yes, needs to be parked for now then.

**Comment by bridadan** [comment]
Ok, I'll go ahead and close this then since it sounds like that change is being reverted. If the plans change again please let us know @deepikabhavnani @geky @0xc0170, thanks!

**Pull request closed without merging**
